SET check_function_bodies = false;
SELECT pg_catalog.setval('public.workspaces_id_seq', 1, false);
INSERT INTO public.workspaces (name, description, workspace_type_id, amenities, capacity, area, street, city_id, contact_no, email, website, am, pm, "from", "to")
VALUES ('Room 1', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Ut etiam sit amet nisl purus in mollis nunc sed. Turpis nunc eget lorem dolor sed viverra ipsum nunc.', 1, '{"Refreshments","Smart TV","Whiteboard"}', 20, 'Bondi Junction, Sydney NSW', '33 Bondi Road, Bondi Junction NSW 2000', 1, '+61 02 924 577', 'reception@space.com', 'www.space.com', 't', 't', '09:00:00+00', '18:00:00+00');
INSERT INTO public.workspaces (name, description, workspace_type_id, amenities, capacity, area, street, city_id, contact_no, email, website, am, pm, "from", "to")
VALUES ('Room 2', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Ut etiam sit amet nisl purus in mollis nunc sed. Turpis nunc eget lorem dolor sed viverra ipsum nunc.', 1, '{"Refreshments","Smart TV","Whiteboard"}', 20, 'Bondi Junction, Sydney NSW', '33 Bondi Road, Bondi Junction NSW 2000', 1, '+61 02 924 577', 'reception@space.com', 'www.space.com', 't', 'f', '08:00:00+00', '12:00:00+00');
INSERT INTO public.workspaces (name, description, workspace_type_id, amenities, capacity, area, street, city_id, contact_no, email, website, am, pm, "from", "to")
VALUES ('Room 3', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Ut etiam sit amet nisl purus in mollis nunc sed. Turpis nunc eget lorem dolor sed viverra ipsum nunc.', 1, '{"Refreshments","Smart TV","Whiteboard"}', 20, 'Bondi Junction, Sydney NSW', '33 Bondi Road, Bondi Junction NSW 2000', 1, '+61 02 924 577', 'reception@space.com', 'www.space.com', 'f', 't', '13:00:00+00', '17:00:00+00');
INSERT INTO public.workspaces (name, description, workspace_type_id, amenities, capacity, area, street, city_id, contact_no, email, website, am, pm, "from", "to")
VALUES ('Room 4', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Ut etiam sit amet nisl purus in mollis nunc sed. Turpis nunc eget lorem dolor sed viverra ipsum nunc.', 1, '{"Refreshments","Smart TV","Whiteboard"}', 20, 'Bondi Junction, Sydney NSW', '33 Bondi Road, Bondi Junction NSW 2000', 1, '+61 02 924 577', 'reception@space.com', 'www.space.com', 'f', 'f', '07:00:00+00', '17:00:00+00');
INSERT INTO public.workspaces (name, description, workspace_type_id, amenities, capacity, area, street, city_id, contact_no, email, website, am, pm, "from", "to")
VALUES ('Room 5', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Adipiscing commodo elit at imperdiet. Ut consequat semper viverra nam libero justo laoreet sit. Ut etiam sit amet nisl purus in mollis nunc sed. Turpis nunc eget lorem dolor sed viverra ipsum nunc.', 1, '{"Refreshments","Smart TV","Whiteboard"}', 20, 'Bondi Junction, Sydney NSW', '33 Bondi Road, Bondi Junction NSW 2000', 1, '+61 02 924 577', 'reception@space.com', 'www.space.com', 't', 't', '08:00:00+00', '17:00:00+00');
